ALTER TABLE users
    ADD COLUMN IF NOT EXISTS provider    VARCHAR(50)  NOT NULL DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS provider_id VARCHAR(255);

ALTER TABLE users ALTER COLUMN password DROP NOT NULL;
